import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Providers } from "@/redux/provider";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={sans.className}>
      <body >
        <Providers>
          <header>
            <Navbar />
          </header>

          {children}
        </Providers>
      </body>
    </html>
  );
}
