version : "2"

services:
  nginxproxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Asiz/Seoul
networks:
  backend:
    driver: bridge